name: CI

on:
  push:
    branches: ["**"]
    tags:
      - 'v*'
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test

  release:
    name: Build and Release (tagged)
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker build -t lecture-qa:${IMAGE_TAG} .
          docker image save -o lecture-qa-${IMAGE_TAG}.tar lecture-qa:${IMAGE_TAG}
          sha256sum lecture-qa-${IMAGE_TAG}.tar > lecture-qa-${IMAGE_TAG}.sha256

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lecture-qa-${{ github.ref_name }}.tar
            lecture-qa-${{ github.ref_name }}.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
